spring:
  application:
    name: VoteApplication
  datasource:
    url: jdbc:postgresql://******/vote?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false;autoReconnect=true
    driver-class-name: org.postgresql.Driver
    username: 
    password:
  #配置druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  initialSize: 5
  maxActive: 20
  filters: stat
  maxWait: 60000
  validationQuery: select 'x'
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20

  #Redis服务器地址
redis:
  host: 127.0.0.1
  port: 6379      #Redis服务器连接端口
  database: 0     #Redis数据库索引（默认为0）
  jedis:
    pool:
      max-active: 50      #连接池最大连接数（使用负值表示没有限制）
      max-wait: 3000      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 20        #连接池中的最大空闲连接
      min-idle: 2         #连接池中的最小空闲连接
  timeout: 5000           #连接超时时间（毫秒）

mybatis:
  mapper-locations: classpath:mapper/*.xml
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servle:
      content-type: text/html
server:
  port: 9007
  servlet:
    context-path: /
